name: Run XML Translator Every 4 Hours

on:
  schedule:
    - cron: "0 */4 * * *" # Every 4 hours
  workflow_dispatch: # Allow manual run from GitHub

jobs:
  run-translator:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install deep-translator forex-python requests

      - name: Run translation script
        run: python translate_xml.py
