name: Translate XML and update files

on:
  schedule:
    - cron: "0 */4 * * *" # every 4 hours at minute 0
  workflow_dispatch: # allows manual trigger

jobs:
  translate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python 3.x
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install deep-translator forex-python

      - name: Run translatexml_ayakkabi.py
        run: python translatexml_ayakkabi.py

      - name: Run translatexml_icgiyim.py
        run: python translatexml_icgiyim.py

      - name: Commit and push updated XML files
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add translatedsample_ayakkabi.xml translatedsample_icgiyim.xml
          if ! git diff --cached --quiet; then
            git commit -m "Update translated XML files"
            git push
          else
            echo "No changes to commit"
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
